repos:
  - repo: local
    hooks:
      - id: grund-config-validate
        name: grund config validate
        entry: grund config validate
        language: system
        pass_filenames: false
        always_run: true
      - id: grund-check
        name: grund check
        entry: grund check .
        language: system
        pass_filenames: false
        always_run: true
